language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "M/bhzoFNHkN7eQpQ3jivJbqyINobL63BAVCHB6ywN7OQV12RLurIVgsTK8IHkWK3oY+D8RascTMpRcghDNnu5E/jp5sfSVu063J5Dxy+F2r+S53TnSxX3Qc7UeLuRBnVoec1/FsNugy5XL24Od+AOYdTteA1KtaNhvNwBUoBoqiHe3NfqoR/yOMY8mvIqA4PTqALXMOlyVQCp+xXviTBID4DunzVxRtHJHlIiVhiIn31sQLI5vnXo6X6TFSJHMW0sqhZea/9AWwmKIrTwpGdniT0euN/xdPm17jMPN73DlI/2y4fXx65Lx2kXHPbemwVilW8sxoSICS1UwRJuWJHk6DjjcmBqro855ZNfw0DAyaR/pTrJgpJN6sgB/jIh6eAOsDEsOPcPcAezuTAJh8dHSEr/vvnvtAocQv/iy75spP/EgQqbtwbndFZ5K/7O25T6UU5Jkazlon7UnYbNFzTTYcr0EFepL1Gvky49FaoqvDea3xZc4O1zy8DAWqqTHrCnOuCRlAsOQtOFbjqcBVPIdW/jlpfI7udEYzuGcSZ7VCJuv4Pl+cx9CjwiJqljaTAmD7YEMiDKhq1snqHS5b19eu/VzmgNkS2GyJbmfcaONEI6skcTMrzTJ58ATcbCMNZrqGY7ttZ/ki1EHpT38G9Ovw7R4bGljbkjZ3B/DHjDNA="
  api_key: # abeb
    secure: "dN1mJPB70dNk3kj/hXELBzWxjHdh52DT30u9FBtb4CvDacBj03JxnT9Cwb/36QArDIpnl0j3uPDZKMys1FxdQwpWBwVPSX5Ahc6Zjcw8rINOy9FV5iKegxtOGTeKAB3i/SO3zRimVOvUEYgllqHbjabtTSiV2Ry4CYecdxvS4H1WxaoxAfOQlTflWtdiyYyQBq1BCylwoLZ4hk1+myaG4IHypbt7FCx+IJFU9VUpTp34unLJib3mfijo9cCB0gmhPaCYX86U+zCAmAtCHLXBzSRHETeQUT6TRyAVgYMdqKxG20sfx4kPZOmz2I5zVYYZdWKW1mGr3GBnEFrg4VHKEgJOrQdpdmB8ITZDMXXtKDYaIYwFcl/1eIPDPmeS24LiS9LvwH9wjhqEh+pLjRxgV8Ax60kYm9xVrTyN6T5X3n+GM4ZR8/lhJz2NYMoxHvghBC7MvEYq1sLhyyACQO8dBh+ade2l3KmV+Wp3s0hiVxsYalrcE3WFhMjpgvP/uI1RKqpxHjwSKVbSd8A7ieBdbrJR/JT1b/u49Q1ieH90UDikbab2HLro0ow9agOylw3XREBEEubv6bU8pREz+BYeTmXBekru/L3lZRh/+a6zpHLEj+tsOdksA0ork85K5Q4dzNBPY1SfbNnhhOPgvKlwOh0/BpuWADSJCuZVcrvm/mU="
  on:
    tags: true
    node: lts/*
