language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "dkAgx2h1niyi5B9Um02wr1+Hk9IqwrtOrZGHzWJUsU1fE396mVoUa3s2UTSFvQtUA5ZLmVb9Wo/M52+DjIkj2/wUkWZtMwZtXanNnkGpmU0XpniChNIeK+vbj84TriK42mKfeS7KDlYuEUQPm4huEoAoPTLd504arD6aMTfipMuP7uzBfVhGasTgv3D4sCWaRu+CUK26PM3LjH4u+eyipfNBRKTtDi6js+Sy4n2v5i1/jVXx5bzdq40HXnB6HpAAo99RryaLZUtmSYcV/EntbECPT02Pgnkb4lKVg12L+pmrZnEeImTBJu19EnI5BethJxKB6OCaeRvqSfLPww+ykh8vlpuBH8FhB0yNhLM/WAFUO97/3TuGfxTp1s5NTTRkWYiCN/Prq/Y72f87j7RSSRWMl5AeWKQxhd7LtsGiJPDqGuPU2PMGf8hUzqwBtotkST/mS4JmhXPUXmb5w7vF78fxZkxnlhq3X9mFPuHSp3K+ExIHQhJBbiOP7Ise5HnTFGoNJuNa6bNltLzB5r2d9ZijGeoN4gBeC+LvqPCUqadD1DIaEMFjCLwpdxu2dJZpQ1RLlQ5MQllN5Q7qZ73Cpa79IIEXs6ZFx7bjdJ7FANROZHD0ZGonTOk3Aa4dgAQL5W+cy7eGUG3zxzTAXEmxBS+g+IUKSG1+LfApvBEZKKg="
  api_key: # 849f
    secure: "Oz2ajmWJAyYCbAMoBwU6+iiywqxAnrdjtSJQeUvp5MDYGhZFt0uz8gRxetgqzzYrxfkx/XKmx4Bt5F7q8l4+fjvdFbff7NTAjuJ5M07NYDx+0SBG+NV0veUsCfChbcprnIWYe8TBjuP8ZdMZJXgnPsKNpgzWwuIi30khZCoEVA1XUlPCgsYcW8s6ZDUMGG6e4P0GFXqXzmBs6dVn1A6khFXOoPFES9kKeraj3b9BQ9QzHAQcoIs2ldTSZymoZTZmAceq4ihEhap/zmsIgejROBQdH8FD3VtJAPRSQMaq/2bQIJ5OAhP9SdnRCsGn/xtJ0TGAYXu4lbr26KP8fYdsd1yvFKxebZrMFDl7M/Sc3J53a1bkGdCGyZhkQ5y6SLv4axSvV0KZlzrldgFzCaFFct2wiZHXfhI8NZfbGSmVVTH8UVpGjXVXInIlMwvxOGz0bANt/4rwxIdUjTyQ/zWRVaqNFKZQUo/v4IdokLF8+TJXimtzeUQ9Wnh76hrd7HJIFfLSdO8rIbI66LfWaB83DbiIPat8vg0A8pdL0+ZYamRGbU0gmkyP8IVa7SlHmSTEL2BczZroPHrkyJTCL4eH85tNli7E5URINaGzbUZL/HtjTeSCOhWhKNhRab3JYXQiYQW8phTeHU7x7Sv/YIgC2fplqQXfhadvaYZneRgKyn0="
  on:
    tags: true
    node: lts/*
